### ISSUE TITLE
Vehicles not showing up in the scenario

### ISSUE THREAD

**Issue by Mohamed-Fasil** [carla-simulator/traffic-generation-editor#10]
Hello,

I followed the instructions specified in the documentation to create a scenario using the QGIS plugin. When I place a camera and hit play scenario, the pygame window opens up with the map but I can't see any vehicles in it.  It just seems to be a static image.  

I also tried using different vehicles as well just to make sure it is not an issue with just one vehicle.

Please let me know if I am missing something.

Thanks!!

**Comment by fabianoboril** [comment]
Hi,
if do not define any maneuvers or such, the scenario itself will terminate immediately. Thus, you will not see any vehicles/actors. You can just add a "dummy" maneuver for on of the actors, for example to start driving after 10 seconds. This should help you to see the actors.

**Comment by Mohamed-Fasil** [comment]
Hello,

I did add a dummy maneuver for the actors to start driving after 5 secs, but unfortunately I am still facing the same error. May be I am doing something wrong with respect to adding the the maneuver. It would be really helpful if there is a video explaining the right way to create and run the scenario.

**Comment by fabianoboril** [comment]
@seowwj Can you add a tutorial video?

**Comment by Mohamed-Fasil** [comment]
@fabianoboril  I tried creating different scenarios but still this issue persists.

**Comment by Mohamed-Fasil** [comment]
Hello @fabianoboril  and @seowwj !! I tried the same on a Linux machine as well but unfortunately the issue persists. Request your help on this one as we have struck at this particular step. Thanks!!

**Comment by fabianoboril** [comment]
I can't recreate this problem. Could you do a screen recording that you can share? And please check that you use the latest versions.

**Comment by Mohamed-Fasil** [comment]
https://user-images.githubusercontent.com/31707333/133506090-7e7ca215-4f95-4754-8998-4631ae922517.mp4

Hello @fabianoboril !! Please find the attached screen share. Thanks for the immediate response.

**Comment by fabianoboril** [comment]
Did you try to run the scenario directly with ScenarioRunner? Maybe SR crashes immediately on your system.

**Comment by fabianoboril** [comment]
I did some more testing, and I am not able to reproduce your issue. Can you please check to run the exported scenario directly with ScenarioRunner (python3 $SCENARIO_RUNNER_ROOT/scenario_runner.py --openscenario <path/to/your/file>)?

**Comment by Mohamed-Fasil** [comment]
Hello @fabianoboril !! Sorry for the delay, I was installing the entire setup in a Ubuntu only laptop just to make sure I eliminate the VM issues. This is the error I get when I try to run the exported openscenario with scenario runner
![Screenshot from 2021-09-21 13-03-46](https://user-images.githubusercontent.com/31707333/134215851-7e5d6b59-b31b-49d6-a57d-67d9560e4743.png)

**Comment by fabianoboril** [comment]
This is a strange error. Did you create the trial.xosc with the scenario editor? Can you share the file here?

**Comment by Mohamed-Fasil** [comment]
Hello @fabianoboril !! I think I figured it out, I didn't give a waypoint for all the vehicles and because of that the vehicles didn't show up. As a suggestion, it would be really helpful if you can mention to give waypoints to all the vehicles in the documentation such that it will be helpful for new users like me. Thanks for helping me debug this issue.

**Comment by Mohamed-Fasil** [comment]
![Screenshot from 2021-10-06 13-17-26](https://user-images.githubusercontent.com/31707333/136252701-55bd53ee-5aeb-4f7f-8a1d-90e0f0eb27e8.png)

Whenever I try creating a scenario, I get the above error and the pygmae window appears dark

**Comment by fabianoboril** [comment]
Ok, that shouldn't happen. I will try to take a look.

**Comment by FENGShuanglang** [comment]
I have the same question.when I click Play Scenario ,it only appears a still picture. it work well run the /tmp/scenariogenerate1.XOSC file with ScenarioRunner(python $SCENARIO_RUNNER_ROOT/scenario_runner.py --openscenario <path/to/your/file> ), 
I think the main reason is 'Popen(["python …"])' , But I create a py file coding with  'Popen(["python …"])'  , it works well . So what is the real reason? Please help me. By the way I find a bug, you miss the key 'RelDistType ' in code

**Comment by Mohamed-Fasil** [comment]
@fabianoboril  We are trying to promote this solution to our customers as well, hence it would be really helpful if we can figure out this issue. Thanks in advance.

**Comment by ronyshaji** [comment]
@Mohamed-Fasil Did you ever tried to find a solution?

**Comment by Anhar2** [comment]
Could you find a solution to this issue?
