### ISSUE TITLE
does this traffic-generation-editor can be used in windows

### ISSUE THREAD

**Issue by yaoshu666** [carla-simulator/traffic-generation-editor#12]

**Comment by yaoshu666** [comment]
Hello,
Is there windows support for this package?
Thanks!

**Comment by fabianoboril** [comment]
QGIS is available for Windows, and this plugin is Python (so can work as well). The core question hence must be, is the map plugin compatible with Windows. I suggest to ask there for help.

**Comment by yaoshu666** [comment]
> QGIS 适用于 Windows，这个插件是 Python（所以也可以工作）。因此，核心问题必须是地图插件是否与 Windows 兼容。我建议去那里寻求帮助。

When I run qgis and install the plugin from the plugins menu (Plugins > Manage and Install Plugins > Install from ZIP), choose the zip file that was previously downloaded,it shows ''No module named 'ad_map_access' ''.however, ad-map-access python only for linux. Is there windows support for this package?

**Comment by fabianoboril** [comment]
Let's close this issue for the time. If ad-map-access works with windows, this tool should work as well.
