### ISSUE TITLE
Ability to load existing scenarios?

### ISSUE THREAD

**Issue by ellislm** [carla-simulator/traffic-generation-editor#3]
First of all. Excellent work on this tool. This is exactly what my team has been looking for. I've managed to get some simple scenarios created, but I'm wondering if it's currently possible to load in previously-created scenarios? It would be worthwhile to be able retrieve and edit pre-existing scenarios.

**Comment by fabianoboril** [comment]
Hi @loganimation 

thanks for the feedback. In fact, we are currently working on loading pre-existing XOSC files.
