### ISSUE TITLE
pygame window not opening up

### ISSUE THREAD

**Issue by Mohamed-Fasil** [carla-simulator/traffic-generation-editor#5]
When I run the manual control python code from scenario runner separately it runs fine but the pygame window doesn't open when running through the plugin. 
These are the steps followed
1.  Load Town01.xodr using  the Carla ad_map_access plugin
2.  Create a scenario using the Openscenario plugin
3.  Connect to Carla 
4.  Play the scenario

Note: I am running Ubuntu 20.04..2 LTS and python 3.8.10 on a VM with a single M60 GPU and NVIDIA drivers

**Comment by fabianoboril** [comment]
Hi,
can you provide some more details, on the steps that you perform? I cannot reproduce your issue.

Just to clarify: You should connect to CARLA, and load the map you want to use, _before_ creating the scenario. In addition, you should place a camera, before playing the scenario.

**Comment by fabianoboril** [comment]
I just added a new commit that improves the handling of the carla connection plugin. Maybe this resolves some of your issues.

**Comment by Mohamed-Fasil** [comment]
> I just added a new commit that improves the handling of the carla connection plugin. Maybe this resolves some of your issues.

That worked thanks a lot!!
